package py.com.mabit.enums;

public enum TipoSanitizacion {
	VACUNACION, DESPARASITACION_INTERNA, DESPARASITACION_EXTERNA, ANTIBIOTICO, SUPLEMENTO_VITAMINICO, MINERALIZACION,
	HIGIENE_Y_LIMPIEZA, HORMONOTERAPIA, TRATAMIENTO_ANTIINFLAMATORIO, TRATAMIENTO_ANTIPIRETICO, TRATAMIENTO_ANTI_ESTRES,
	ANALGESICO, INSPECCION_SANITARIA, PROFILAXIS_RESPIRATORIA, PROFILAXIS_DIGESTIVA, CONTROL_DE_REPRODUCCION,
	TRATAMIENTO_ANTIFUNGICO, DESINFECCION_DE_HERIDAS, TRATAMIENTO_ANTI_ANEMIA, INMUNOMODULADOR
}
